### ISSUE TITLE
Load mp3 files

### ISSUE THREAD

**Issue by legendvijay** [fgnm/Audio3DEngine#1]
I want to know how to load mp3, Its accepting .wav only.
I just want to know is there any luck for you ?

**Comment by fgnm** [comment]
Please describe what you need so I can try to help you..

**Comment by fgnm** [comment]
Hi, mp3 files can be played as well as any other format.. You have just read official Resonance Audio docs, you have to use a Mono mp3. Usually mp3 has always two audio tracks (for stereo purpose), just edit your mp3 with Audacity and remove one channel.

**Comment by legendvijay** [comment]
Ok Thanks, I will try that.
